### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by Camelia03** [Camelia03/portofolio-project-4#2]
- [ ] Camelia03/portofolio-project-4#21 
- [ ] Camelia03/portofolio-project-4#20 
- [ ] Camelia03/portofolio-project-4#19
- [ ] Camelia03/portofolio-project-4#18
