### ISSUE TITLE
Replies

### ISSUE THREAD

**Issue by Camelia03** [Camelia03/portofolio-project-4#23]
- [ ] Camelia03/portofolio-project-4#13
- [ ] Camelia03/portofolio-project-4#12
- [ ] Camelia03/portofolio-project-4#4 
- [ ] Camelia03/portofolio-project-4#5
