### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by Camelia03** [Camelia03/portofolio-project-4#24]
- [ ] - Camelia03/portofolio-project-4#27
- [ ] - Camelia03/portofolio-project-4#26
- [ ] - Camelia03/portofolio-project-4#28
