### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by Camelia03** [Camelia03/portofolio-project-4#25]
- [ ] Camelia03/portofolio-project-4#1
- [ ] Camelia03/portofolio-project-4#6
- [ ] Camelia03/portofolio-project-4#15
- [ ] Camelia03/portofolio-project-4#16
- [ ] Camelia03/portofolio-project-4#17
