### ISSUE TITLE
Upvote and downvote

### ISSUE THREAD

**Issue by Camelia03** [Camelia03/portofolio-project-4#42]
- [ ] Camelia03/portofolio-project-4#11
- [ ] Camelia03/portofolio-project-4#32
- [ ] Camelia03/portofolio-project-4#37
