### ISSUE TITLE
Admin's actions

### ISSUE THREAD

**Issue by Camelia03** [Camelia03/portofolio-project-4#48]
- [ ] Camelia03/portofolio-project-4#7
- [ ] Camelia03/portofolio-project-4#8
- [ ] Camelia03/portofolio-project-4#33
