### ISSUE TITLE
Functionalities

### ISSUE THREAD

**Issue by Camelia03** [Camelia03/portofolio-project-4#50]
- [ ] Camelia03/portofolio-project-4#29
- [ ]  Camelia03/portofolio-project-4#30
- [ ] Camelia03/portofolio-project-4#43
- [ ] Camelia03/portofolio-project-4#44
